In [7]:
from py_experimenter.experimenter import PyExperimenter
import pandas as pd

# Get Data

In [8]:
experimetner = PyExperimenter(experiment_configuration_file_path="conf/experiment_config.yml",
                              database_credential_file_path="conf/database_credentials.yml")

2026-01-24 09:27:43,852  | py-experimenter - INFO     | Found 9 keyfields
INFO:py-experimenter:Found 9 keyfields
2026-01-24 09:27:43,854  | py-experimenter - INFO     | Found 8 resultfields
INFO:py-experimenter:Found 8 resultfields
2026-01-24 09:27:43,855  | py-experimenter - INFO     | Found 1 logtables
INFO:py-experimenter:Found 1 logtables
2026-01-24 09:27:43,856  | py-experimenter - INFO     | Found logtable priorbai_experiments__sh_iterations
INFO:py-experimenter:Found logtable priorbai_experiments__sh_iterations
2026-01-24 09:27:43,857  | py-experimenter - WARNING  | No custom section defined in config
WARNING:py-experimenter:No custom section defined in config
2026-01-24 09:27:43,858  | py-experimenter - WARNING  | No codecarbon section defined in config
WARNING:py-experimenter:No codecarbon section defined in config
2026-01-24 09:27:44,003  | py-experimenter - INFO     | Initialized and connected to database
INFO:py-experimenter:Initialized and connected to database

In [9]:
table = experimetner.get_table()
table.to_csv("explored_data.csv", index=False)

logtable = experimetner.get_logtable("sh_iterations")
logtable.to_csv("explored_logdata.csv", index=False)

# Load Data

In [10]:
table = pd.read_csv("explored_data.csv")
logtable = pd.read_csv("explored_logdata.csv")

In [11]:
table

          ID    run_id  num_arms  ... best_arm             end_date error
0          1  __AUTO__        32  ...      1.0  2026-01-24 08:41:01   NaN
1          2  __AUTO__        64  ...      1.0  2026-01-24 08:33:37   NaN
2          3  __AUTO__       128  ...      1.0  2026-01-24 08:41:00   NaN
3          4  __AUTO__       256  ...      1.0  2026-01-24 08:25:16   NaN
4          5  __AUTO__        32  ...      0.0  2026-01-24 08:37:24   NaN
...      ...       ...       ...  ...      ...                  ...   ...
11995  11996  __AUTO__       256  ...      1.0  2026-01-24 08:25:45   NaN
11996  11997  __AUTO__        32  ...      0.0  2026-01-24 08:31:28   NaN
11997  11998  __AUTO__        64  ...      0.0  2026-01-24 08:35:08   NaN
11998  11999  __AUTO__       128  ...      0.0  2026-01-24 08:32:25   NaN
11999  12000  __AUTO__       256  ...      0.0  2026-01-24 08:43:02   NaN

[12000 rows x 25 columns]

In [12]:
logtable

          ID  experiment_id  ... budget_spent_so_far        N_stop
0          1           7993  ...                32.0  0.000000e+00
1          2           8354  ...                64.0  1.377170e+08
2          3           8289  ...                32.0  5.131354e+07
3          4           6931  ...               128.0  1.822616e+11
4          5           4451  ...               128.0  3.585278e+08
...      ...            ...  ...                 ...           ...
62232  62233            760  ...              1024.0  2.358531e+03
62233  62234            760  ...              1152.0  1.093322e+03
62234  62235           4672  ...               768.0  1.976529e+05
62235  62236           4672  ...               896.0  1.239015e+07
62236  62237           4672  ...              1024.0  5.448658e+02

[62237 rows x 8 columns]