In [2]:
from py_experimenter.experimenter import PyExperimenter
import pandas as pd

# Get Data

In [3]:
experimetner = PyExperimenter(experiment_configuration_file_path="conf/experiment_config.yml",
                              database_credential_file_path="conf/database_credentials.yml")

2026-01-24 09:34:15,670  | py-experimenter - INFO     | Found 9 keyfields
2026-01-24 09:34:15,671  | py-experimenter - INFO     | Found 8 resultfields
2026-01-24 09:34:15,671  | py-experimenter - INFO     | Found 1 logtables
2026-01-24 09:34:15,672  | py-experimenter - INFO     | Found logtable priorbai_experiments__sh_iterations
2026-01-24 09:34:15,672  | py-experimenter - WARNING  | No custom section defined in config
2026-01-24 09:34:15,672  | py-experimenter - WARNING  | No codecarbon section defined in config
2026-01-24 09:34:15,832  | py-experimenter - INFO     | Initialized and connected to database

In [4]:
table = experimetner.get_table()
table.to_csv("explored_data.csv", index=False)

logtable = experimetner.get_logtable("sh_iterations")
logtable.to_csv("explored_logdata.csv", index=False)

# Load Data

In [5]:
table = pd.read_csv("explored_data.csv")
logtable = pd.read_csv("explored_logdata.csv")

In [6]:
table

,ID,run_id,num_arms,benchmark,seed,prior,performance_prior_std,sigma0,epsilon,delta,...,T_max,consumed_budget,remaining_arms,num_epsilon_optimal_arms,arm_id_selected,regret,epsilon_optimal,best_arm,end_date,error
0,1,__AUTO__,32,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,32.0,96.0,1.0,1.0,0.0,0.000000,1.0,1.0,2026-01-24 08:41:01,NaN
1,2,__AUTO__,64,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,64.0,224.0,1.0,2.0,0.0,0.000000,1.0,1.0,2026-01-24 08:33:37,NaN
2,3,__AUTO__,128,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,128.0,512.0,1.0,2.0,0.0,0.000000,1.0,1.0,2026-01-24 08:41:00,NaN
3,4,__AUTO__,256,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,256.0,1152.0,1.0,2.0,0.0,0.000000,1.0,1.0,2026-01-24 08:25:16,NaN
4,5,__AUTO__,32,lcbench,0,uniform,0.01,0.0100,0.01,0.05,...,52.0,96.0,1.0,3.0,16.0,0.107090,0.0,0.0,2026-01-24 08:37:24,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,11996,__AUTO__,256,synthetic,99,indicator,0.01,0.0001,0.01,0.05,...,256.0,1152.0,1.0,5.0,0.0,0.000000,1.0,1.0,2026-01-24 08:25:45,NaN
11996,11997,__AUTO__,32,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,52.0,96.0,1.0,1.0,1.0,0.031307,0.0,0.0,2026-01-24 08:31:28,NaN
11997,11998,__AUTO__,64,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,52.0,224.0,1.0,3.0,1.0,0.007482,1.0,0.0,2026-01-24 08:35:08,NaN
11998,11999,__AUTO__,128,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,52.0,512.0,2.0,1.0,1.0,0.017697,0.0,0.0,2026-01-24 08:32:25,NaN
11999,12000,__AUTO__,256,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,52.0,1152.0,1.0,1.0,4.0,0.032924,0.0,0.0,2026-01-24 08:43:02,NaN

In [7]:
logtable

,ID,experiment_id,timestamp,iteration,num_arms,best_arm_included,budget_spent_so_far,N_stop
0,1,7993,2026-01-24 08:22:45,0,32,1,32.0,0.000000e+00
1,2,8354,2026-01-24 08:22:45,0,64,1,64.0,1.377170e+08
2,3,8289,2026-01-24 08:22:45,0,32,1,32.0,5.131354e+07
3,4,6931,2026-01-24 08:22:45,0,128,1,128.0,1.822616e+11
4,5,4451,2026-01-24 08:22:45,0,128,1,128.0,3.585278e+08
...,...,...,...,...,...,...,...,...
62232,62233,760,2026-01-24 08:43:56,6,4,0,1024.0,2.358531e+03
62233,62234,760,2026-01-24 08:43:57,7,2,0,1152.0,1.093322e+03
62234,62235,4672,2026-01-24 08:43:56,4,16,0,768.0,1.976529e+05
62235,62236,4672,2026-01-24 08:43:58,5,8,0,896.0,1.239015e+07
62236,62237,4672,2026-01-24 08:43:58,6,4,0,1024.0,5.448658e+02

In [8]:
joined_table = pd.merge(table, logtable, left_on="ID", right_on="experiment_id")

In [9]:
joined_table

,ID_x,run_id,num_arms_x,benchmark,seed,prior,performance_prior_std,sigma0,epsilon,delta,...,end_date,error,ID_y,experiment_id,timestamp,iteration,num_arms_y,best_arm_included,budget_spent_so_far,N_stop
0,1,__AUTO__,32,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,2026-01-24 08:41:01,NaN,53933,1,2026-01-24 08:40:59,0,32,1,32.0,5.131354e+07
1,1,__AUTO__,32,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,2026-01-24 08:41:01,NaN,53947,1,2026-01-24 08:40:59,1,16,1,48.0,2.563061e+07
2,1,__AUTO__,32,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,2026-01-24 08:41:01,NaN,54008,1,2026-01-24 08:40:59,2,8,1,64.0,1.281531e+07
3,1,__AUTO__,32,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,2026-01-24 08:41:01,NaN,54017,1,2026-01-24 08:41:00,3,4,1,80.0,6.407575e+06
4,1,__AUTO__,32,synthetic,0,uniform,0.01,0.0100,0.01,0.05,...,2026-01-24 08:41:01,NaN,54021,1,2026-01-24 08:41:00,4,2,1,96.0,3.026242e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62232,12000,__AUTO__,256,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,2026-01-24 08:43:02,NaN,59693,12000,2026-01-24 08:42:59,3,32,0,640.0,1.366045e+08
62233,12000,__AUTO__,256,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,2026-01-24 08:43:02,NaN,59731,12000,2026-01-24 08:42:59,4,16,0,768.0,6.504651e+07
62234,12000,__AUTO__,256,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,2026-01-24 08:43:02,NaN,59746,12000,2026-01-24 08:42:59,5,8,0,896.0,3.009791e+07
62235,12000,__AUTO__,256,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,2026-01-24 08:43:02,NaN,59754,12000,2026-01-24 08:43:00,6,4,0,1024.0,4.780639e+03
62236,12000,__AUTO__,256,lcbench,99,indicator,0.01,0.0001,0.01,0.05,...,2026-01-24 08:43:02,NaN,59786,12000,2026-01-24 08:43:00,7,2,0,1152.0,2.224641e+03